language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: SYMFONY="4.4"

    - php: 7.2
      env: SYMFONY="4.4"
    - php: 7.2
      env: SYMFONY="5.1"

    - php: 7.3
      env: SYMFONY="4.4"
    - php: 7.3
      env: SYMFONY="5.1"

    - php: 7.4
      env: SYMFONY="4.4"
    - php: 7.4
      env: SYMFONY="5.1"
    - php: 7.4
      env: SYMFONY="5.2" STABILITY="dev"

    - php: 8.0
      env: SYMFONY="5.1"

  allow_failures:
    - php: 7.4
      env: SYMFONY="5.2" STABILITY="dev"
    - php: 8.0
      env: SYMFONY="5.1"

before_script:
  - travis_retry composer self-update
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - travis_retry composer require "symfony/framework-bundle:${SYMFONY}" --no-interaction --prefer-dist

script:
  - composer test
