name: tests

on:
    push:
    pull_request:
    schedule:
        -   cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    -   php: 7.1
                        symfony: 4.4

                    -   php: 7.2
                        symfony: 4.4
                    -   php: 7.2
                        symfony: 5.1

                    -   php: 7.3
                        symfony: 4.4
                    -   php: 7.3
                        symfony: 5.1

                    -   php: 7.4
                        symfony: 4.4
                    -   php: 7.4
                        symfony: 5.1

                    -   php: 8.0
                        symfony: 5.1

        name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip
                    tools: composer:v2
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "symfony/framework-bundle:${{ matrix.symfony }}" --no-interaction --no-update
                    composer update --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit --verbose
